### PR TITLE
Added pod affinity support

### LINKED ISSUE #580: Missing nodeSelector for search and hazelcast/clustering service pods
**Is your feature request related to a problem? Please describe.**
Have kubernetes cluster containing both Linux and Windows worker nodes so would like to have the ability to add node selector for the Search and Hazelcast/Clustering Service pods. This feature is already present for all the other pods created from the Web, Batch, or Stream tiers.

**Describe the solution you'd like**
Ability to add node selector for the search and Hazelcast/Clustering pods to launch the pod on specific node.

**Describe alternatives you've considered**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by alemax22**
Added pod affinity support in:
- Pega chart for deployment of: 
  - Hazelcast
  - Elasticsearch (for Pega < 8.6)
  - Tiers pods
  - Install / Upgrade jobs
- BackingServices chart for deployment of:
  - SRS service
  - Constellation
  - Constellation messaging service
Updated the documentations of all the above charts in order to describe how to adopt the pod affinity feature in the charts.
Resolves #580

### CODE REVIEW

**Comment by MadhuriArugula** [comment]
@Anand-Kotamsetti @nikhilparmar86 Can you please review the changes from respective sub charts?

**Review by bhowd1 — COMMENTED** [review]
From SRS helm chart POV, changes looks good to me!!

Before approving it wanted to know that, did we test these changes by deploying it locally also can we add tests for the same in [terratest/src/test/backingservices/srs-deployment_test.go](https://github.com/pegasystems/pega-helm-charts/blob/master/terratest/src/test/backingservices/srs-deployment_test.go) ?

Thanks

**Comment by MadhuriArugula** [comment]
@alemax22 Can you add corresponding tests for all the referenced deployments in this PR ? Also would you be able to resolve the conflicts?

**Comment by alemax22** [comment]
@MadhuriArugula   unit tests created for every deployment modified and updated branch with the last changes from the master

**Review by bhowd1 — APPROVED** [review]
Changes look good to me from SRS helm chart end!!

**Review by MadhuriArugula — APPROVED** [review]

**Comment by MadhuriArugula** [comment]
@npjohnson637 Can you review the PR for constellation chart.

**Review by nikhilparmar86 — APPROVED** [review]

**Review by arvasrikanth — APPROVED** [review]

**Pull request merged**
