### PR TITLE
US-622676 - helm chart changes for tcp keep alive probe

### PR DESCRIPTION
**Pull request by Saurabh-16**

### CODE REVIEW

**Comment by pegaautomationuser** [comment]
Starting PR-837 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-837 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-837 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-837 validation on -> configs

**Review by arvasrikanth — APPROVED** [review]

**Comment by pegaautomationuser** [comment]
Starting PR-837 validation on -> configs

**Review by kingakowalska1 — CHANGES_REQUESTED** [review]
Hi Saurabh,

Just a small suggestion. Please change the following text: 

Starting from Kubernetes 1.29 version, kubernetes allows to set OS kernel level setting `net.ipv4.tcp_keepalive_time` using standard sysctls command.
Please refer below example and if needed, provide the value in seconds as per the cloud provider TCP connections timeout settings.

To:

Starting in Kubernetes version 1.29, you can configure the OS Kernel level setting `net.ipv4.tcp_keepalive_time` using standard sysctls command. To configure the setting, provide 
The following code provides an example configuration. If needed, provide the value in seconds as per the cloud provider TCP connections timeout settings.

Thanks!
Kinga

**Comment by pegaautomationuser** [comment]
Starting PR-837 validation on -> configs

**Review by kingakowalska1 — APPROVED** [review]
Looks good!

**Review by pega-talba — APPROVED** [review]

**Comment by APegaDavis** [comment]
@Saurabh-16 is this only needed for runtime or should we be doing the same for the installer?

**Review by misterdorito — APPROVED** [review]

**Comment by Saurabh-16** [comment]
> @Saurabh-16 is this only needed for runtime or should we be doing the same for the installer?
Hi @APegaDavis :- Currently its only for runtime use cases. This is a request from GOC as their TCP connections are timing out while making external server calls. Chances are extended to CMC and will be adopted in cloudk.

**Pull request merged**
