### PR TITLE
Add responseTime in localhost access logs #412

### PR DESCRIPTION
**Pull request by shashikant-koder**
Added responseTime and thread name in localhost access logs

### CODE REVIEW

**Comment by pegaautomationuser** [comment]
Starting PR-414 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-414 validation on -> configs

**Review by NekhilKotha — APPROVED** [review]

**Review by kishorv10 — APPROVED** [review]

**Comment by pegaautomationuser** [comment]
Starting PR-414 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-414 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-414 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-414 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-414 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-414 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-414 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-414 validation on -> configs

**Pull request merged**
