### PR TITLE
Add diagram for eks deployment

### PR DESCRIPTION
**Pull request by feenr**
I added a diagram for a recomended approach to deploying the Pega Helm charts on AWS, with some consideration given to high availability.

### CODE REVIEW

**Review by taz-pega-work — CHANGES_REQUESTED** [review]
Can you add a Hazelcast service into the mypega namespace? you add the hazelcast Docker image to the pega values.yaml so when you deploy that namespace, it brings up Hazelcast-dedicated pod

**Review by taz-pega-work — APPROVED** [review]
that looks great. thank you!

**Comment by petejo** [comment]
We should probably identify the versions of Pega this diagram is applicable for.

**Review by taz-pega-work — APPROVED** [review]
looks great! thanks for adding the addons tier

**Review by kingakowalska1 — APPROVED** [review]
Looks great!

**Comment by MadhuriArugula** [comment]
@feenr Are we good to merge this PR?

**Comment by feenr** [comment]
@MadhuriArugula sorry for ignoring your previous comment. Branch is merged now.

**Pull request merged**
