### PR TITLE
fix: Fixes handling of enable flag

### LINKED ISSUE #533: By default, both SRS & constellation are getting deployed with helm install command
**Describe the bug**
1) By default both SRS & constellation are getting deployed with below helm install command 
$ helm install backingservices pega/backingservices --namespace pegabackingservices --values backingservices.yaml

2) There is no option in the genrated(used below command ) `backingservices.yaml` to disable constellation depployment.
$ helm inspect values pega/backingservices > backingservices.yaml

**To Reproduce**
1) use the below command to generate backingservices.yaml
$ helm inspect values pega/backingservices > backingservices.yaml
2)Fill up with appropriate values in backingservices.yaml
3)Run `$ helm install backingservices pega/backingservices --namespace pegabackingservices --values backingservices.yaml`

Error :: 

-bash-4.2$ helm install backingservices pega/backingservices --namespace srs-demo --values backingservices.yaml

WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /dsk01/apps/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /dsk01/apps/.kube/config
W0302 19:15:41.436488   25695 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0302 19:15:41.499141   25695 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
Error: INSTALLATION FAILED: Ingress.extensions "constellationingress" is invalid: spec.rules[0].host: Invalid value: "YOUR_CUSTOM_DOMAIN_NAME_HERE": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

**Expected behavior**
Either to have option to choose any service deployment in generated backingservices.yaml

**Chart version**
helm search repo pega
NAME                	CHART VERSION	APP VERSION	DESCRIPTION
pega/pega           	2.8.1        	           	Pega installation on kubernetes
pega/addons         	2.8.1        	1.0        	A Helm chart for Kubernetes
pega/backingservices	2.8.1        	           	Helm Chart to provision the latest Search and R...

### PR DESCRIPTION
**Pull request by sotoiwa**
Fix #533

Ingress and Secret resources did not process the enable flag. Fixed to process them.
Also, the if conditionals were redundant, changed to simplify.

### CODE REVIEW

**Comment by MadhuriArugula** [comment]
@sotoiwa Can you add unit tests for the changes?

**Comment by sotoiwa** [comment]
@MadhuriArugula I added unit tests. There were no tests for constellation. I only added tests that check for `constellation.enabled`.

**Comment by sotoiwa** [comment]
@MadhuriArugula Can you review this PR?

Also, there is [a suggestion](https://github.com/pegasystems/pega-helm-charts/issues/533#issuecomment-1505363103) to disable Constellation by default, what do you think?

**Comment by anuds20** [comment]
> @MadhuriArugula Can you review this PR?
> 
> Also, there is [a suggestion](https://github.com/pegasystems/pega-helm-charts/issues/533#issuecomment-1505363103) to disable Constellation by default, what do you think?

@sotoiwa Yes you can disable constellation.

**Review by anuds20 — COMMENTED** [review]
Changes look good. Can be merged once constellation is set to be disabled by default.

**Comment by sotoiwa** [comment]
@anuds20 I set constellation to disabled by default in the parent backingservice chart default values.

**Review by anuds20 — APPROVED** [review]

**Comment by sotoiwa** [comment]
@MadhuriArugula @anuds20 I do not have permission to merge this pull request or it looks like I need another review. Can someone please review and merge?

**Review by taz-pega-work — COMMENTED** [review]
how does this fix affect the enabled flag in
charts/backingservices/charts/constellation/values.yaml???

If you have to enable Constellation here, you have to clarify that in the documentation, since the new behavior is disabled by default, right?>>>
charts/backingservices/charts/constellation/README.md

**Review by MadhuriArugula — APPROVED** [review]

**Comment by MadhuriArugula** [comment]
> how does this fix affect the enabled flag in charts/backingservices/charts/constellation/values.yaml???
> 
> Also, if you have to enable Constellation here in the backingservices values.yaml, you have to clarify that in the documentation, since the new behavior is disabled by default, right?>>> charts/backingservices/charts/constellation/README.md

https://github.com/pegasystems/pega-helm-charts/blob/master/charts/backingservices/charts/constellation/README.md#configuration-settings Flag details are already mentioned in the constellation documentation. Will that suffice?

**Review by Saurabh-16 — APPROVED** [review]

**Pull request merged**
