### PR TITLE
support for custom certificates to be injectable to infinity

### PR DESCRIPTION
**Pull request by smootherbug**

### CODE REVIEW

**Review by Heshma — APPROVED** [review]

**Review by taz-pega-work — DISMISSED** [review]
where do we we describe this in the Pega readme? I don't see any mention of this functionality in the pega readme>>https://github.com/pegasystems/pega-helm-charts/tree/master/charts/pega

**Review by taz-pega-work — COMMENTED** [review]
update to>>
Pega supports mounting and passing custom certificates into the tomcat container during your Pega Platform deployment. Pega supports the following certificate formats as long as they are encoded in base64: X.509 certificates such as PEM, DER, CER, CRT. To mount and pass the your custom certificates, use the `certificates` attributes as a map in the `values.yaml` file using the format in the following example.

**Comment by pegaautomationuser** [comment]
Starting PR-359 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-359 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-359 validation on -> configs

**Review by taz-pega-work — APPROVED** [review]
thanks for the enhanced wording. Looks good!

**Comment by pegaautomationuser** [comment]
Starting PR-359 validation on -> configs

**Review by MadhuriArugula — APPROVED** [review]

**Pull request merged**
