### PR TITLE
BUG-868079 Add the option to configure keystore and truststore type for Cassandra connection

### PR DESCRIPTION
**Pull request by wonim2022**
…or cassandra client encryption

### CODE REVIEW

**Review by taz-pega-work — CHANGES_REQUESTED** [review]
For all of the newly added comments, we need Cassandra to be capitalized so these comments have Cassandra consistently capitalized across all of the files. Otherwise, I think the wording looks pretty good.

**Comment by wonim2022** [comment]
Thanks for the reivew, I capitalized all Cassandra occurrences in new comments

**Comment by kingakowalska1** [comment]
Hi,

Could we please tweak the message a bit? My suggestion is as follows:

If required, provide the type of Cassandra truststore and keystore that you used to hold keys and certificates for client encryption. Available store types are JKS and PKCS12. Default is JKS.

Also, in terratest/src/test/pega/data/values_zdt_upgrade_http_non_default_port81.yaml, we should include both available types as well. I would suggest using the same message as in all the other files.

Thanks!
Kinga

**Comment by wonim2022** [comment]
Tweaked the message like you proposed @kingakowalska1

**Review by taz-pega-work — APPROVED** [review]
changes look great. thanks for collaborating!

**Review by kingakowalska1 — APPROVED** [review]
Looks great!

**Review by baylp2022 — APPROVED** [review]

**Comment by taz-pega-work** [comment]
completing this bug fix by merging the fix at the request of Paul Bayliss

**Pull request merged**
