### PR TITLE
TASK-1248241 - changes to pega-deployment for certificate check

### PR DESCRIPTION
**Pull request by Saurabh-16**

### CODE REVIEW

**Comment by pegaautomationuser** [comment]
Starting PR-385 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-385 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-385 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-385 validation on -> configs

**Review by arvasrikanth — APPROVED** [review]

**Review by MadhuriArugula — APPROVED** [review]

**Pull request merged**
