### PR TITLE
Task 1178942 - Need to templatize context.xml.tmpl in different style to support xml parsing

### PR DESCRIPTION
**Pull request by Saurabh-16**
Need to templatize context.xml.tmpl in different style to support xml parsing

### CODE REVIEW

**Review by arvasrikanth — APPROVED** [review]

**Comment by pegaautomationuser** [comment]
Starting PR-327 validation on -> configs

**Review by pega-embate — APPROVED** [review]

**Comment by pegaautomationuser** [comment]
Starting PR-327 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-327 validation on -> integ-eks,configs

**Comment by pegaautomationuser** [comment]
Starting PR-327 validation on -> integ-eks,configs

**Comment by pegaautomationuser** [comment]
Starting PR-327 validation on -> integ-eks,configs

**Review by MadhuriArugula — APPROVED** [review]

**Comment by pegaautomationuser** [comment]
Starting PR-327 validation on -> integ-eks,configs

**Comment by pegaautomationuser** [comment]
Starting PR-327 validation on -> integ-eks,configs

**Comment by pegaautomationuser** [comment]
Starting PR-327 validation on -> integ-eks,configs

**Comment by pegaautomationuser** [comment]
Starting PR-327 validation on -> integ-eks,configs

**Comment by pegaautomationuser** [comment]
Starting PR-327 validation on -> integ-eks,configs

**Pull request merged**
