### PR TITLE
Fb supplementalgroups mod

### PR DESCRIPTION
**Pull request by pegatim**
Please reference the issue https://github.com/pegasystems/pega-helm-charts/issues/659, and do hit me up for comments/questions. Thanks!

### CODE REVIEW

**Comment by micgoe** [comment]
I would appreciate the code owners reviewing the PR. It would be a huge benefit for us as well

**Review by MadhuriArugula — CHANGES_REQUESTED** [review]
Please add unit tests for the new feature.

**Comment by kishorv10** [comment]
#659 
#635

**Comment by kishorv10** [comment]
@pegatim Issue is similar to #635 Can you take a look at it? Can this be addressed in this PR?

**Comment by kishorv10** [comment]
> @pegatim Issue is similar to #635 Can you take a look at it? Can this be addressed in this PR? Looks like both the issues are related to supplementalGroups property

Never mind. It looks Issue-635 is for Search and the current PR (issue-659) is for Pega chart.

**Comment by kishorv10** [comment]
We're closing the current pull request in favor of #750

**Pull request closed without merging**
