### PR TITLE
US-616762 : removal of Embedded Stream support from Infinity '24

### PR DESCRIPTION
**Pull request by raju119**
Embedded Stream support is removed starting from Infinity '24. 
if you are using Embedded Stream and want to upgrade to Infinity '24 then you should externalize Stream service first then upgrade to infinity '24.

### CODE REVIEW

**Comment by kishorv10** [comment]
@raju119 Are you planning to cut a major release with this change? As the upgrade to this versions mandates Infinity version to 24 or above?

**Comment by raju119** [comment]
> @raju119 Are you planning to cut a major release with this change? As the upgrade to this version mandates Infinity version to be 24 or above?

@kishorv10 , there is no Pega version constraint with these changes. However if we are trying to deploy Infinity '24 then we should configure with external Kafka.

1. if customer is on older version of Pega with Embedded Stream and want to upgrade to Infinity '24 then should externalize their Kafka first after that only they should upgrade Pega version to Infinity'24. if they try to upgrade to Infinity '24 with Embedded Stream then Pega engine startup will fail.
2. if the Customer is already using External Stream then upgrading to Infinity '24 won't have any issues from Stream side.
3. if it is a new deployment on Infinity '24 we should always use External Stream.

**Comment by kishorv10** [comment]
> > @raju119 Are you planning to cut a major release with this change? As the upgrade to this version mandates Infinity version to be 24 or above?
> 
> @kishorv10 , there is no Pega version constraint with these changes. However if we are trying to deploy Infinity '24 then we should configure with external Kafka.
> 
> 1. if customer is on older version of Pega with Embedded Stream and want to upgrade to Infinity '24 then should externalize their Kafka first after that only they should upgrade Pega version to Infinity'24. if they try to upgrade to Infinity '24 with Embedded Stream then Pega engine startup will fail.
> 2. if the Customer is already using External Stream then upgrading to Infinity '24 won't have any issues from Stream side.
> 3. if it is a new deployment on Infinity '24 we should always use External Stream.

In this PR, the values.yaml - Stream tier section is removed, implies there wont be a stream node deployment. Clients having a stream node (on older Pega version), if upgraded to newer helm chart version and with the latest values.yaml, that upgrade would cause the stream node to disappear. Similarly, Clients installing the helm chart on lower versions would not get a Stream node. What is expected in these two scenarios with your changes?

**Comment by kishorv10** [comment]
@taz-mon Can you please review the PR?

**Review by kishorv10 — APPROVED** [review]

**Review by MadhuriArugula — APPROVED** [review]

**Comment by MadhuriArugula** [comment]
@kingakowalska1 can you please review the documentation changes

**Review by kingakowalska1 — CHANGES_REQUESTED** [review]
Hi, 

I would suggest the following documentation edits:

In charts/pega/EmbeddedStream.md, the text should read as follows (sections marked (…) are unchanged).

### Embedded Stream with latest helm chart version
Starting from Infinity 24.2, support for embedded Stream is removed. As a best practice, update your Stream configuration to an external Kafka service.
To configure embedded Stream in Pega Platform ’24.1 and earlier using the Pega Helm chart version 3.25, perform the following steps.
1. Add Stream tier details in the values.yaml file under Pega tiers section.
#### Example for values.yaml and values-large.yaml
(…)
[Line 15-16 should read as follows:]
Note: Stream tier is deprecated. As a best practice, enable externalized Kafka service configuration under External Services.
When externalized Kafka service is enabled, remove the entire stream tier.
(…)
#### Example for values-minimal.yaml
For values-minimal.yaml, add the Stream nodeType to the minikube tier.
(…)
[Line 92]
Note: Stream tier is deprecated. As a best practice, enable externalized Kafka service configuration under External Services.
(…)
2.	Disable external Kafka service settings in the values.yaml file.
(…)

In charts/pega/values-minimal.yaml please edit the following note:
[Line 116] Note: The nodeType Stream is not supported, enable externalized Kafka service instead.

The rest of the changes look great, thank you!

Thanks!
Kinga

**Comment by raju119** [comment]
> Hi,
> 
> I would suggest the following documentation edits:
> 
> In charts/pega/EmbeddedStream.md, the text should read as follows (sections marked (…) are unchanged).
> 
> ### Embedded Stream with latest helm chart version
> Starting from Infinity 24.2, support for embedded Stream is removed. As a best practice, update your Stream configuration to an external Kafka service. To configure embedded Stream in Pega Platform ’24.1 and earlier using the Pega Helm chart version 3.25, perform the following steps.
> 
> 1. Add Stream tier details in the values.yaml file under Pega tiers section.
> 
> #### Example for values.yaml and values-large.yaml
> (…) [Line 15-16 should read as follows:] Note: Stream tier is deprecated. As a best practice, enable externalized Kafka service configuration under External Services. When externalized Kafka service is enabled, remove the entire stream tier. (…)
> 
> #### Example for values-minimal.yaml
> For values-minimal.yaml, add the Stream nodeType to the minikube tier. (…) [Line 92] Note: Stream tier is deprecated. As a best practice, enable externalized Kafka service configuration under External Services. (…) 2. Disable external Kafka service settings in the values.yaml file. (…)
> 
> In charts/pega/values-minimal.yaml please edit the following note: [Line 116] Note: The nodeType Stream is not supported, enable externalized Kafka service instead.
> 
> The rest of the changes look great, thank you!
> 
> Thanks! Kinga

Thank you @kingakowalska1 for the review.
I have updated documentation as per the requested changes. could you please review the changes.

Regards,
Narayana Raju

**Review by kingakowalska1 — APPROVED** [review]
Looks good!

**Review by MadhuriArugula — APPROVED** [review]

**Pull request merged**
