### PR TITLE
ISSUE-680 Fix OAuth Client Secret env variable

### LINKED ISSUE #680: SRS OAuth fails with missing private key
**Describe the bug**
The Helm chart adds an env variable SERV_AUTH_PRIVATE_KEY, but we get an error message in the Pega log that says SERV_AUTH_CLIENT_SECRET hasn't been set.

com.pega.platform.securitycore.internal.oauth2.ClientAuthenticationProviderException: Unable to load auth data: [com.pega.platform.securitycore.internal.oauth2.PrivateKeyJWTProvider@31f90517: Incorrect private key: , [com.pega.platform.securitycore.internal.oauth2.ClientSecretBasicProvider@2f6f2d91](mailto:com.pega.platform.securitycore.internal.oauth2.ClientSecretBasicProvider@2f6f2d91): Either SERV_AUTH_CLIENT_ID or SERV_AUTH_CLIENT_SECRET env vars empty

**To Reproduce**
Configure OAuth as described in the documentation

**Expected behavior**
Successful authentication.  This feature begins working if we add to our tier definition:

custom:
  env:
    - name: SERV_AUTH_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: pega-srs-auth-secret
          key: privateKey

**Chart version**
3.10.0

### PR DESCRIPTION
**Pull request by maracle6**
Fixes #680

### CODE REVIEW

**Comment by kishorv10** [comment]
@reddy-srinivas Can you please take a look at the PR?

**Comment by kishorv10** [comment]
@reddy-srinivas @ravitejamekapega Can you please review?

**Review by bhowd1 — APPROVED** [review]
LGTM!! Thanks for the changes.

**Review by APegaDavis — APPROVED** [review]
Cross-checked w/ Search team as well, looks good

**Pull request merged**
