### PR TITLE
Add imagePullSecretNames value to SRS chart

### LINKED ISSUE #653: External image pull secrets for SRS
**Is your feature request related to a problem? Please describe.**
Previously support for external imagePullSecrets was added in #483 for the pega chart.  The SRS chart doesn't yet support this.

**Describe the solution you'd like**
add imagePullSecretNames to the values file, which then adds to the default secret created for the SRS deployment.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by maracle6**
Fixes #653

### CODE REVIEW

**Review by bhowd1 — COMMENTED** [review]
Hi @maracle6 ,
Did we test these changes by removing keeping the `global.imageCredentials.registry, username, password` fields blank? Since these values are used to create the registry secret which is used to pull the images.

**Comment by maracle6** [comment]
@bhowd1 I added your requested updates -- Thanks

**Review by bhowd1 — APPROVED** [review]
Thanks for the updates. Changes looks good to me!

**Review by kingakowalska1 — APPROVED** [review]
Looks great!

**Comment by maracle6** [comment]
@MadhuriArugula This is ready to merge

**Review by MadhuriArugula — APPROVED** [review]

**Pull request merged**
