### PR TITLE
Issue 294 - java.net.UnknownHostException: pega-search-transport: Name or service not known 

### PR DESCRIPTION
**Pull request by Saurabh-16**
. A single ES node was being launched and es-discovery appears to be trying to resolve the DNS before the pod is marked as `Ready`.  The DNS from the stateless service is not being resolved as “Pod needs to become ready in order to have a record unless publishNotReadyAddresses=True is set on the Service.” (from https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/).

### CODE REVIEW

**Review by kishorv10 — APPROVED** [review]

**Review by MadhuriArugula — APPROVED** [review]

**Comment by pegaautomationuser** [comment]
Starting PR-316 validation on -> integ-eks

**Comment by pegaautomationuser** [comment]
Starting PR-316 validation on -> integ-eks

**Comment by pegaautomationuser** [comment]
Starting PR-316 validation on -> integ-eks

**Comment by pegaautomationuser** [comment]
Starting PR-316 validation on -> integ-eks

**Pull request merged**
