### PR TITLE
Templatize action validator yaml file

### PR DESCRIPTION
**Pull request by arvasrikanth**
To override the action validator behavior from cloudk, we need to templatize action validator yaml file

### CODE REVIEW

**Comment by pegaautomationuser** [comment]
Starting PR-334 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-334 validation on -> integ-eks,configs

**Comment by pegaautomationuser** [comment]
Starting PR-334 validation on -> integ-eks,configs

**Comment by pegaautomationuser** [comment]
Starting PR-334 validation on -> integ-eks,configs

**Comment by pegaautomationuser** [comment]
Starting PR-334 validation on -> integ-eks,configs

**Comment by pegaautomationuser** [comment]
Starting PR-334 validation on -> integ-eks,configs

**Comment by pegaautomationuser** [comment]
Starting PR-334 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-334 validation on -> integ-eks

**Comment by pegaautomationuser** [comment]
Starting PR-334 validation on -> integ-eks

**Review by MadhuriArugula — APPROVED** [review]

**Review by kishorv10 — APPROVED** [review]

**Comment by pegaautomationuser** [comment]
Starting PR-334 validation on -> integ-eks

**Comment by pegaautomationuser** [comment]
Starting PR-334 validation on -> integ-eks

**Pull request merged**
