### PR TITLE
reworded the connection details section, along with fixed a typo

### PR DESCRIPTION
**Pull request by Evan1oconto**

### CODE REVIEW

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Review by MadhuriArugula — APPROVED** [review]

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-424 validation on -> configs

**Pull request merged**
