### PR TITLE
Allow server.xml and web.xml overrides in tier configmaps

### PR DESCRIPTION
**Pull request by APegaDavis**
* Allow overrides of Tomcat's server.xml and web.xml
* server.xml default copy included from config/deploy if no override is provided
* No web.xml default is provided, but will be picked up if a copy is placed in config/deploy
* web.xml is not included if no override is provided and the file does not exist in config/deploy

### CODE REVIEW

**Comment by pega-embate** [comment]
Why are we allowing override of these config files?  Isn't the point of the prweb config to specify params that we want to have complete control of in k8s deployments?

**Comment by pega-embate** [comment]
Assuming server.xml is still in the base image as well, how can we ensure they are kept in synch?

**Comment by APegaDavis** [comment]
> Why are we allowing override of these config files? Isn't the point of the prweb config to specify params that we want to have complete control of in k8s deployments?

My mistake -- we want to allow override of server.xml and web.xml (not prweb.xml). I'll update my PR.

The goal is to allow customization of these files without having to provide additional enhancements every time a new category of customization is discovered, which has been a problem in the past.

> Assuming server.xml is still in the base image as well, how can we ensure they are kept in synch?

Since the base image is specific to a particular platform version it might make sense to do the same for both server and web and remove the server.xml default from here -- only providing a value via helm charts if an override is provided.

**Comment by pega-embate** [comment]
> Since the base image is specific to a particular platform version it might make sense to do the same for both server and web and remove the server.xml default from here -- only providing a value via helm charts if an override is provided.

I think it makes sense to remove the default server.xml from here

**Comment by APegaDavis** [comment]
> > Since the base image is specific to a particular platform version it might make sense to do the same for both server and web and remove the server.xml default from here -- only providing a value via helm charts if an override is provided.
> 
> I think it makes sense to remove the default server.xml from here

Default server.xml removed and associated test has been updated.

**Review by pega-embate — APPROVED** [review]

**Review by misterdorito — APPROVED** [review]

**Comment by NekhilKotha** [comment]
@APegaDavis  Can we add documentation for newly injectable files. https://github.com/pegasystems/pega-helm-charts/tree/master/charts/pega#pega-configuration-files

**Review by NekhilKotha — CHANGES_REQUESTED** [review]
Can we add documentation for newly injectable files. https://github.com/pegasystems/pega-helm-charts/tree/master/charts/pega#pega-configuration-files

**Review by NekhilKotha — APPROVED** [review]

**Review by taz-pega-work — CHANGES_REQUESTED** [review]
<!-- Note:  A "Server" is not itself a "Container", so you may not
     define subcomponents such as "Valves" at this level.
     Documentation at /docs/config/server.html

While most of the comments appropriately describe what you edit in the yaml, this one doesn't say what the port defines here or what shutdown is.

**Comment by APegaDavis** [comment]
With latest changes (and reflected in the updated PR description):
* Allow overrides of server.xml and web.xml via values.yaml
* Provide default server.xml in config/deploy directory
* No default provided for web.xml (it is Pega Platform release-specific)
* If a web.xml is added to config/deploy directory, it will be used as the default during template rendering
* If no web.xml exists in config/deploy and no web.xml override is provided, it will not be included

**Review by taz-pega-work — APPROVED** [review]
documentation content looks good.

**Pull request merged**
