### PR TITLE
DO NOT MERGE: Added Support for authentication for downloading JDBC driver

### PR DESCRIPTION
**Pull request by Heshma**
Added Support for authentication either through basic authentication or api key for downloading JDBC driver

### CODE REVIEW

**Comment by pegaautomationuser** [comment]
Starting PR-406 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-406 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-406 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-406 validation on -> configs

**Comment by pegaautomationuser** [comment]
Starting PR-406 validation on -> configs

**Comment by Heshma** [comment]
Will reopen with README changes merged.

**Pull request closed without merging**
